// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product.proto

package products

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Price struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{0}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Price) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Discount             bool     `protobuf:"varint,3,opt,name=discount,proto3" json:"discount,omitempty"`
	ImageURL             string   `protobuf:"bytes,4,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	Price                *Price   `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{1}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDiscount() bool {
	if m != nil {
		return m.Discount
	}
	return false
}

func (m *Product) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *Product) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

type Discount struct {
	DiscountID           string   `protobuf:"bytes,1,opt,name=discountID,proto3" json:"discountID,omitempty"`
	Summary              string   `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{2}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetDiscountID() string {
	if m != nil {
		return m.DiscountID
	}
	return ""
}

func (m *Discount) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProductDetail struct {
	Description          string    `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Discount             *Discount `protobuf:"bytes,2,opt,name=discount,proto3" json:"discount,omitempty"`
	Product              *Product  `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProductDetail) Reset()         { *m = ProductDetail{} }
func (m *ProductDetail) String() string { return proto.CompactTextString(m) }
func (*ProductDetail) ProtoMessage()    {}
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{6}
}

func (m *ProductDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductDetail.Unmarshal(m, b)
}
func (m *ProductDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductDetail.Marshal(b, m, deterministic)
}
func (m *ProductDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductDetail.Merge(m, src)
}
func (m *ProductDetail) XXX_Size() int {
	return xxx_messageInfo_ProductDetail.Size(m)
}
func (m *ProductDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ProductDetail proto.InternalMessageInfo

func (m *ProductDetail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProductDetail) GetDiscount() *Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

func (m *ProductDetail) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Price)(nil), "products.Price")
	proto.RegisterType((*Product)(nil), "products.Product")
	proto.RegisterType((*Discount)(nil), "products.Discount")
	proto.RegisterType((*ListRequest)(nil), "products.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "products.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "products.GetRequest")
	proto.RegisterType((*ProductDetail)(nil), "products.ProductDetail")
}

func init() { proto.RegisterFile("proto/product.proto", fileDescriptor_cfd9ed8e6077aee0) }

var fileDescriptor_cfd9ed8e6077aee0 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5d, 0x4b, 0xfb, 0x30,
	0x14, 0xc6, 0xd7, 0xee, 0xad, 0xff, 0xd3, 0xff, 0x26, 0x46, 0x9d, 0x65, 0x88, 0x94, 0x80, 0x30,
	0x10, 0x2b, 0x4c, 0xd0, 0x2b, 0xef, 0x0a, 0x43, 0xd8, 0xc5, 0xe8, 0xf0, 0x03, 0x74, 0x6d, 0x90,
	0xc0, 0xfa, 0x62, 0x92, 0x0a, 0xbb, 0xf4, 0x5e, 0xfc, 0xcc, 0xd2, 0xbc, 0xb4, 0x65, 0x7a, 0x97,
	0xe7, 0x9c, 0x9c, 0x27, 0xcf, 0xf9, 0x11, 0x38, 0x2b, 0x59, 0x21, 0x8a, 0xfb, 0x92, 0x15, 0x69,
	0x95, 0x88, 0x40, 0x2a, 0xe4, 0x68, 0xc9, 0xf1, 0x16, 0x86, 0x1b, 0x46, 0x13, 0x82, 0x66, 0x30,
	0xe2, 0x87, 0x6c, 0x57, 0xec, 0x3d, 0xcb, 0xb7, 0x16, 0xff, 0x22, 0xad, 0xd0, 0x1c, 0x9c, 0xa4,
	0x62, 0x8c, 0xe4, 0xc9, 0xc1, 0xb3, 0x65, 0xa7, 0xd1, 0xf5, 0x4c, 0x9c, 0x15, 0x55, 0x2e, 0xbc,
	0xbe, 0x9a, 0x51, 0x0a, 0x7f, 0x59, 0x30, 0xde, 0xa8, 0x17, 0xd0, 0x14, 0x6c, 0x9a, 0x6a, 0x4f,
	0x9b, 0xa6, 0x08, 0xc1, 0x20, 0x8f, 0x33, 0xa2, 0xbd, 0xe4, 0xb9, 0x7e, 0x23, 0xa5, 0x3c, 0x69,
	0x9c, 0x9c, 0xa8, 0xd1, 0x75, 0x8f, 0x66, 0xf1, 0x1b, 0x79, 0x8d, 0xd6, 0xde, 0x40, 0xbd, 0x6f,
	0x34, 0xba, 0x81, 0x61, 0x59, 0x87, 0xf7, 0x86, 0xbe, 0xb5, 0x70, 0x97, 0x27, 0x81, 0x59, 0x2b,
	0x90, 0x3b, 0x45, 0xaa, 0x8b, 0x43, 0x70, 0x42, 0x63, 0x77, 0x0d, 0x60, 0xac, 0x5f, 0x42, 0x1d,
	0xab, 0x53, 0x41, 0x1e, 0x8c, 0x79, 0x95, 0x65, 0x31, 0x33, 0xdb, 0x1a, 0x89, 0x27, 0xe0, 0xae,
	0x29, 0x17, 0x11, 0x79, 0xaf, 0x08, 0x17, 0xf8, 0x19, 0xfe, 0x2b, 0xc9, 0xcb, 0x22, 0xe7, 0x04,
	0xdd, 0x41, 0x03, 0xd5, 0xb3, 0xfc, 0xfe, 0xc2, 0x5d, 0x9e, 0x76, 0xe3, 0xc8, 0x43, 0xd4, 0x72,
	0xbf, 0x02, 0x58, 0x11, 0x63, 0x76, 0x0c, 0x09, 0x7f, 0x5b, 0x30, 0xd1, 0x33, 0x21, 0x11, 0x31,
	0xdd, 0x23, 0x1f, 0xdc, 0x94, 0xf0, 0x84, 0xd1, 0x52, 0xd0, 0x22, 0xd7, 0x57, 0xbb, 0x25, 0x14,
	0x74, 0x20, 0xda, 0x92, 0x07, 0x6a, 0x03, 0x98, 0xfd, 0x3b, 0x60, 0x6f, 0x61, 0xac, 0xdb, 0x92,
	0xf9, 0x9f, 0x79, 0xcd, 0x8d, 0xe5, 0xa7, 0x05, 0x53, 0x5d, 0xdc, 0x12, 0xf6, 0x51, 0x7f, 0x98,
	0x27, 0x18, 0xd4, 0x00, 0xd0, 0x45, 0x3b, 0xd6, 0xe1, 0x33, 0x9f, 0x1d, 0x97, 0x15, 0x27, 0xdc,
	0x43, 0x8f, 0xd0, 0x5f, 0x11, 0x81, 0xce, 0xdb, 0x0b, 0x2d, 0x89, 0xf9, 0xe5, 0xaf, 0x10, 0x0a,
	0x00, 0xee, 0xed, 0x46, 0xf2, 0xef, 0x3e, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x7b, 0xb6,
	0xb4, 0xd2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProductService service

type ProductServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*ProductDetail, error)
}

type productServiceClient struct {
	c           client.Client
	serviceName string
}

func NewProductServiceClient(serviceName string, c client.Client) ProductServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "products"
	}
	return &productServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *productServiceClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*ProductDetail, error) {
	req := c.c.NewRequest(c.serviceName, "ProductService.Get", in)
	out := new(ProductDetail)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceHandler interface {
	List(context.Context, *ListRequest, *ListResponse) error
	Get(context.Context, *GetRequest, *ProductDetail) error
}

func RegisterProductServiceHandler(s server.Server, hdlr ProductServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ProductService{hdlr}, opts...))
}

type ProductService struct {
	ProductServiceHandler
}

func (h *ProductService) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.ProductServiceHandler.List(ctx, in, out)
}

func (h *ProductService) Get(ctx context.Context, in *GetRequest, out *ProductDetail) error {
	return h.ProductServiceHandler.Get(ctx, in, out)
}
